In [ ]:
# numpy : numeric python : 리스트 : 숫자 배열
# 리터널 : 정수, 실수, 문자열
# 부울
# 리스트, 튜플, 딕셔너리, 집합

In [1]:
!pip install numpy

In [2]:
import numpy # 숫자 배열
num = numpy.random.randint(10) # 0 ~ 9
print(num)

0


In [3]:
import numpy as np
num = np.random.randint(10) # 0 ~ 9
print(num)

9


In [8]:
### 배열을 만드는 3가지 방법
#1. random객체를 사용하는 방법
# 1차원 배열 : 벡터(vector)
num = np.random.randint(1, 10, 3) # 3 : size
print(num)
num = np.random.randint(1, 10, size=3) # 3 : size
print(num)
# 2차원 배열
num2 = np.random.randint(1, 10, size=(3, 2))
print(num2)
num2 = np.random.randint(1, 10, size=(2, 3))
print(num2)

[8 7 2]
[1 5 7]
[[4 9]
 [7 8]
 [9 1]]
[[4 3 3]
 [7 1 6]]


In [41]:
# 2. arange()함수를 사용하는 방법
for i in range(9):
  print(i, end =" ")
print()
print("====" * 15)
# 1차원 배열
num = np.arange(10)
print(num)
num = np.arange(11, 21)
print(num)
# 2차원 배열
num2 = np.arange(12).reshape(3, 4)
num2
num2 = np.arange(12).reshape(4, 3)
num2
# num2 = np.arange(10).reshape(2, 6)
# num2
num1 = np.arange(11 , 11+12) # 1차원 배열
print(num1)
num2 = np.arange(11 , 11+12).reshape(2, 6) # 2차원 배열
print(num2)
num1 = np.arange(1 , 1+3)
num1
# 열(column)이 하나인 2차원 배열
num2 = np.arange(1 , 1+3).reshape(3, 1)
num2
# 행(row)이 하나인 2차원배열로 만드시오.
num2 = np.arange(1 , 1+3).reshape(1, 3)
num2
print("=="* 30)
my_arr = np.arange(1000000)
my_arr
my_arr = np.arange(1_000_000)
my_arr

0 1 2 3 4 5 6 7 8 
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20 21 22]
[[11 12 13 14 15 16]
 [17 18 19 20 21 22]]


array([     0,      1,      2, ..., 999997, 999998, 999999])

In [31]:
#3. array()함수를 사용하는 방법: 리스트, 튜플
# 1 차원
num1 = np.array([1, 2, 3])
print(num1)
num1 = np.array((1, 2, 3))
print(num1)
l = [1, 2, 3]
num1 = np.array(l)
print(num1)
# 2 차원 배열
l2 = [[1,2,3,4],[5,6,7,8]]
l2[0]
print(l2)# 리스트
num2 = np.array(l2) # 배열
print(num2)
# 누락값
l2 = [[1,4,np.nan,5],[5,np.nan,8,4], [3,5,8,np.nan]]
print(l2)
num2 = np.array(l2)
num2

[1 2 3]
[1 2 3]
[1 2 3]
[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1, 4, nan, 5], [5, nan, 8, 4], [3, 5, 8, nan]]


array([[ 1.,  4., nan,  5.],
       [ 5., nan,  8.,  4.],
       [ 3.,  5.,  8., nan]])

In [39]:
z = np.zeros(10) # 1차원 0행열
print(z)
z = np.ones(10)
print(z)
# 2차원
z = np.zeros(10).reshape(10,1)
print(z)
z = np.ones(10).reshape(10,1)
print(z)
z = np.zeros(9).reshape(3,3)
print(z)
z = np.ones(9).reshape(3,3)
print(z)
z = np.empty((2, 3))
print(z)
#             면 행 열
z = np.empty((2, 3, 2))
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2.0e-323 1.5e-323 1.5e-323]
 [3.5e-323 4.9e-324 3.0e-323]]
[[[5.43e-323 5.93e-323]
  [6.42e-323 6.92e-323]
  [7.41e-323 7.91e-323]]

 [[8.40e-323 8.89e-323]
  [9.39e-323 9.88e-323]
  [1.04e-322 1.09e-322]]]


In [48]:
# 배열의 데이터 유형
num = np.arange(15)
num
print(num.dtype)
arr1 = np.array([1, 2, 3])
arr1
print(arr1.dtype)
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1
print(arr1.dtype)
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr1
print(arr1.dtype)

int64
int64
float64
int32


In [54]:
 # 타입 변경하기
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.astype(np.int64)) # 실수를 정수로 변경하면 절삭된다

int64
[1. 2. 3. 4. 5.]
float64
[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [61]:
int_array = np.arange(10)
print(int_array)
print(int_array.dtype)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(calibers.dtype) # float64
converted = int_array.astype(calibers.dtype)
print(converted.dtype)

[0 1 2 3 4 5 6 7 8 9]
int64
float64
float64
