In [ ]:
# numpy : numeric python : 리스트 : 숫자 배열
# 리터널 : 정수, 실수, 문자열
# 부울
# 리스트, 튜플, 딕셔너리, 집합

In [1]:
!pip install numpy

In [2]:
import numpy # 숫자 배열
num = numpy.random.randint(10) # 0 ~ 9
print(num)

0


In [3]:
import numpy as np
num = np.random.randint(10) # 0 ~ 9
print(num)

9


In [8]:
### 배열을 만드는 3가지 방법
#1. random객체를 사용하는 방법
# 1차원 배열 : 벡터(vector)
num = np.random.randint(1, 10, 3) # 3 : size
print(num)
num = np.random.randint(1, 10, size=3) # 3 : size
print(num)
# 2차원 배열
num2 = np.random.randint(1, 10, size=(3, 2))
print(num2)
num2 = np.random.randint(1, 10, size=(2, 3))
print(num2)

[8 7 2]
[1 5 7]
[[4 9]
 [7 8]
 [9 1]]
[[4 3 3]
 [7 1 6]]


In [18]:
# 2. arange()함수를 사용하는 방법
for i in range(9):
  print(i, end =" ")
print()
print("====" * 15)
# 1차원 배열
num = np.arange(10)
print(num)
num = np.arange(11, 21)
print(num)
# 2차원 배열
num2 = np.arange(12).reshape(3, 4)
num2
num2 = np.arange(12).reshape(4, 3)
num2
# num2 = np.arange(10).reshape(2, 6)
# num2

0 1 2 3 4 5 6 7 8 
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])