In [1]:
!pip install pandas

In [ ]:
# 판다 시작하기
# 리터널 : 정수 , 실수 , 문자열
# 부울
# 파이썬 : 리스트 , 튜플, 딕셔너리, 집합
# numpy : 숫자 배열 : 리스트
# pandas : 시리즈 : 1차원배열 : 벡터 : 리스트 : 값이 1개인 딕셔너리
#          DataFrame : 2차원배원 : 값이 2개이상인 딕셔너리

In [15]:
import pandas as pd
# 시리즈
obj = pd.Series([4, 7, -5, 3])
print(obj)
print(obj[0])
print(obj.index)

0    4
1    7
2   -5
3    3
dtype: int64
4
RangeIndex(start=0, stop=4, step=1)


In [14]:
import numpy as np
arr = obj.to_numpy() # 1차원 배열
print(arr)
print(obj)
print(np.sum(obj))
print(np.sum(arr))

[ 4  7 -5  3]
0    4
1    7
2   -5
3    3
dtype: int64
RangeIndex(start=0, stop=4, step=1)
9
9


In [20]:
obj = pd.Series([4, 7, -5, 3])
print(obj)
print(obj[0])

0    4
1    7
2   -5
3    3
dtype: int64
4


In [30]:
obj = pd.Series([4, 7, -5, 3], index = ['a','b','c','d'])
print(obj)
print(obj['a']) # 명시적 index
# print(obj[0]) # 암시적 index
l = [1,2,3,4]
print(l[0])
#print(l[0,1,2])
arr =  np.array([1,2,3,4])
print(arr[0])
print(arr[[0,1,2]])
print(obj[['a','b','c']])

a    4
b    7
c   -5
d    3
dtype: int64
4
1
1
[1 2 3]
a    4
b    7
c   -5
dtype: int64


In [33]:
print(arr)
print(arr[arr > 2]) # 부울 index
print(obj[obj > 2])

[1 2 3 4]
[3 4]
a    4
b    7
d    3
dtype: int64


In [37]:
# in 연산자
print( 'a' in obj) # obj에 index가 있는지 확인
print( 0 in obj)
print('e' in obj)

True
False
False


In [41]:
# 딕셔너리를 이용한 시리즈
dic = obj.to_dict()
print(dic)
sdata = pd.Series({"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000})
print(sdata) # 딕셔너리의 키는 시리즈의 index가 됨
dic1 = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
sdata1 = pd.Series(dic1)
print(sdata)

{'a': 4, 'b': 7, 'c': -5, 'd': 3}
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64


In [48]:
dic1 = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
sdata1 = pd.Series(dic1, index=["California", "Ohio", "Oregon", "Texas"])
print(sdata1)
# NaN : 누락값
print(pd.isna(sdata1))
print(pd.notna(sdata1))
print(sdata1.isna())

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool
California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool
California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool


In [53]:
#  연산
print(sdata)
print(sdata1)
print(sdata + sdata1) # index끼리의 연산이 된다.
sdata.name="이숭무" # 시이즈에 이름 주기
sdata.index.name='state' # index에 이름 주기
print(sdata)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64
state
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
Name: 이숭무, dtype: int64


In [54]:
# index 순서 바꾸기
sdata.index=['Oregon','Utah','Ohio','Texas']
print(sdata)

Oregon    35000
Utah      71000
Ohio      16000
Texas      5000
Name: 이숭무, dtype: int64


In [60]:
# 데이터 프레임
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df = pd.DataFrame(data)
df
df.head() # 5개 행   n=5
df.head(n=3)
df.head(n=7)
df.tail()
df.tail(n= 3)

state  year  pop
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [61]:
# 열의 순서를 변경하면서 dataframe 만들기
df1 = pd.DataFrame(data, columns=['year','pop','state'])
df1

year  pop   state
0  2000  1.5    Ohio
1  2001  1.7    Ohio
2  2002  3.6    Ohio
3  2001  2.4  Nevada
4  2002  2.9  Nevada
5  2003  3.2  Nevada

In [67]:
# 열을 출력
df2 = pd.DataFrame(data, columns=['year','pop','state','debt'])
print(df2)
print(df2['state'])
print(type(df2['state']))
print(df2.state)
print(df2['state'][0])

   year  pop   state debt
0  2000  1.5    Ohio  NaN
1  2001  1.7    Ohio  NaN
2  2002  3.6    Ohio  NaN
3  2001  2.4  Nevada  NaN
4  2002  2.9  Nevada  NaN
5  2003  3.2  Nevada  NaN
0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object
<class 'pandas.core.series.Series'>
0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object
Ohio


In [77]:
# 행출력
print(df2)
print(df2['year'])
#print(df2[0])
print(df2.loc[0])
l = [1,2,3,4]
print(l)
print(l[0]) # 암시적 index
print(df2.loc[2]) # 명시적 index
print(df2.iloc[2]) # 암시적 index
print(df2.iloc[-4])  # 암시적 index
# print(df2.loc[-4])

   year  pop   state debt
0  2000  1.5    Ohio  NaN
1  2001  1.7    Ohio  NaN
2  2002  3.6    Ohio  NaN
3  2001  2.4  Nevada  NaN
4  2002  2.9  Nevada  NaN
5  2003  3.2  Nevada  NaN
0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64
year     2000
pop       1.5
state    Ohio
debt      NaN
Name: 0, dtype: object
[1, 2, 3, 4]
1
year     2002
pop       3.6
state    Ohio
debt      NaN
Name: 2, dtype: object
year     2002
pop       3.6
state    Ohio
debt      NaN
Name: 2, dtype: object
year     2002
pop       3.6
state    Ohio
debt      NaN
Name: 2, dtype: object


In [80]:
print(df2)
df2['debt'] = 16.5
print(df2)

   year  pop   state debt
0  2000  1.5    Ohio  NaN
1  2001  1.7    Ohio  NaN
2  2002  3.6    Ohio  NaN
3  2001  2.4  Nevada  NaN
4  2002  2.9  Nevada  NaN
5  2003  3.2  Nevada  NaN
   year  pop   state  debt
0  2000  1.5    Ohio  16.5
1  2001  1.7    Ohio  16.5
2  2002  3.6    Ohio  16.5
3  2001  2.4  Nevada  16.5
4  2002  2.9  Nevada  16.5
5  2003  3.2  Nevada  16.5


In [81]:
df2['debt'] = np.arange(6,) #  0   5의 값으로 순차적으로 채움
print(df2)

   year  pop   state  debt
0  2000  1.5    Ohio     0
1  2001  1.7    Ohio     1
2  2002  3.6    Ohio     2
3  2001  2.4  Nevada     3
4  2002  2.9  Nevada     4
5  2003  3.2  Nevada     5


In [83]:
val = pd.Series([-1.2, -1.5, -1.7], index=[2, 4, 5])
print(val)
df2['debt'] = val # dataFrame의 열 index와 Series의 index가 같은 index만 값이 채워짐
df2

2   -1.2
4   -1.5
5   -1.7
dtype: float64


year  pop   state  debt
0  2000  1.5    Ohio   NaN
1  2001  1.7    Ohio   NaN
2  2002  3.6    Ohio  -1.2
3  2001  2.4  Nevada   NaN
4  2002  2.9  Nevada  -1.5
5  2003  3.2  Nevada  -1.7

In [87]:
# 부울 index
print(df2["state"] == "Ohio")
df2["eastern"] = df2["state"] == "Ohio"
df2
# 딕셔너리와 동일하게 열(키)이 있는 수정 열이 없으면 추가

0     True
1     True
2     True
3    False
4    False
5    False
Name: state, dtype: bool


year  pop   state  debt  eastern
0  2000  1.5    Ohio   NaN     True
1  2001  1.7    Ohio   NaN     True
2  2002  3.6    Ohio  -1.2     True
3  2001  2.4  Nevada   NaN    False
4  2002  2.9  Nevada  -1.5    False
5  2003  3.2  Nevada  -1.7    False

In [90]:
print(df2)
print(df2['eastern'])
del df2['eastern']
df

   year  pop   state  debt  eastern
0  2000  1.5    Ohio   NaN     True
1  2001  1.7    Ohio   NaN     True
2  2002  3.6    Ohio  -1.2     True
3  2001  2.4  Nevada   NaN    False
4  2002  2.9  Nevada  -1.5    False
5  2003  3.2  Nevada  -1.7    False
0     True
1     True
2     True
3    False
4    False
5    False
Name: eastern, dtype: bool


state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [92]:
print(df2.columns) # 컬럼명을 출력

Index(['year', 'pop', 'state', 'debt'], dtype='object')


In [99]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, # index
               "Nevada": {2001: 2.4, 2002: 2.9}}
df3 = pd.DataFrame(populations)
print(df3)
print(df3.T)
df4 = pd.DataFrame(populations , index=[2001,2002,2003])
print(df4)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9
      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN


In [105]:
# Series에 대한 indexing과 Slicing
print(df3)
print(df3['Ohio'])
print(df3['Ohio'][2001])
print(df3['Ohio'][:])
print(df3['Ohio'][:-1]) # 2002 전까지 # 암시적 index
print(df3['Ohio'][:2])

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
2000    1.5
2001    1.7
2002    3.6
Name: Ohio, dtype: float64
1.7
2000    1.5
2001    1.7
2002    3.6
Name: Ohio, dtype: float64
2000    1.5
2001    1.7
Name: Ohio, dtype: float64
2000    1.5
2001    1.7
Name: Ohio, dtype: float64


In [109]:
print(df3)
pdata = {"Ohio" : df3['Ohio'][:-1],
         "Nevada" : df3['Nevada'][:2]}
print(pdata)
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
{'Ohio': 2000    1.5
2001    1.7
Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
2001    2.4
Name: Nevada, dtype: float64}


Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [113]:
df3.name = '이수무'
df3.columns.name = '이장범'
df3.index.name='이상범'
df3

이장범   Ohio  Nevada
이상범               
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [114]:
df3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [122]:
# column이 있는지
print("Ohio" in df3.columns)
# index가 있는지
print(2002 in df3.index)
print(df3.columns)

True
True
Index(['Ohio', 'Nevada'], dtype='object', name='이장범')


In [123]:
# Reindexing
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [125]:
print(obj)
obj2 = obj.reindex(["a", "b", "c", "d", "e"]) # index의 순서 변경
print(obj2)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64
a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64


In [129]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
print(obj3)
reindexed = obj3.reindex(np.arange(6), method='ffill')
print(reindexed)
reindexed = obj3.reindex(np.arange(6), method='bfill')
print(reindexed)

0      blue
2    purple
4    yellow
dtype: object
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object
0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object


In [131]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
print(frame)
frame2 = frame.reindex(index=["a", "b", "c", "d"]) # index를 재정의 할 경우 없던 index에는 값이 NaN이 된다.
print(frame2)

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0


In [145]:
print(frame)
print(frame['Ohio'])
print(type(frame['Ohio']))
print(frame.loc['a'])
print(type(frame.loc['a']))
print(frame.loc['a']['Ohio'])
print(frame.loc[['a','c','d']])
print(type(frame.loc[['a','c','d']]))
print(frame.loc[['a','c','d']]['Ohio'])
print(frame.loc[['a','c','d']][['Ohio','Texas']])

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
a    0
c    3
d    6
Name: Ohio, dtype: int64
<class 'pandas.core.series.Series'>
Ohio          0
Texas         1
California    2
Name: a, dtype: int64
<class 'pandas.core.series.Series'>
0
   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
<class 'pandas.core.frame.DataFrame'>
a    0
c    3
d    6
Name: Ohio, dtype: int64
   Ohio  Texas
a     0      1
c     3      4
d     6      7


In [157]:
print(frame)
print(frame.loc[['a','c','d']]) # 명시적 index
print(frame.iloc[[0,1,2]])

print(frame.loc[['a','c','d']][['Ohio','Texas']]) # 명시적 index , dataFrame 비추
# print(frame.iloc[[0,1,2]][[0,1]]) # 암시적 index

# 강추 : [행, 열]
print(frame.loc[['a','c','d'], ['Ohio','Texas']]) # 행열
print(frame.iloc[[0,1,2], [0,1]]) # 행열

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas
a     0      1
c     3      4
d     6      7
   Ohio  Texas
a     0      1
c     3      4
d     6      7
   Ohio  Texas
a     0      1
c     3      4
d     6      7


In [158]:
# 항목 삭제
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
print(obj)
new_obj = obj.drop("c") # drop함수를 이용해서 해당 index를 삭제할 수 있다.
print(new_obj)
new_obj = obj.drop(["d", "c"])
print(new_obj)

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
e    4.0
dtype: float64


In [159]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [166]:
new_data = data.drop(index=["Colorado", "Ohio"]) # DataFrame에서는 행당 index행을 삭제할 수 있다.
print(new_data)
new_data = data.drop(columns=["two"]) # columns 키워드를 이용하여 컬럼을 삭제
print(new_data)
new_data = data.drop("two", axis=1)  # axis=1은 열을 의미 한다. (행기준, y축기준)
print(new_data)
new_data = data.drop(["two", "four"], axis="columns")
print(new_data)
new_data = data.drop(["Ohio", "Colorado"], axis=0) #  axis=0은 행을 의미 (열 기준 , x축 기준)
print(new_data)
new_data = data.drop(["Ohio", "Colorado"], axis="index") #  axis=0은 행을 의미 (열 기준 , x축 기준)
print(new_data)

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15
          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15
          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15
          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14
          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15


In [167]:
# Indexing, Selection, and Filtering
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
print(obj)
print(obj["b"]) #명시적 index
print(obj[1]) # 암시적 index
print(obj[2:4]) # 암시적 index를 이용한 slicing
print(obj[["b", "a", "d"]]) # 명시적
print(obj[[1, 3]]) # 암시적
print(obj[obj < 2]) # 부울 index

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64
1.0
1.0
c    2.0
d    3.0
dtype: float64
b    1.0
a    0.0
d    3.0
dtype: float64
b    1.0
d    3.0
dtype: float64
a    0.0
b    1.0
dtype: float64


/tmp/ipython-input-2116006461.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(obj[1])
/tmp/ipython-input-2116006461.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(obj[[1, 3]])


In [173]:
print(obj)
print(obj.loc[["b", "a", "d"]]) # Series에서 loc사용
print(obj.iloc[[1,0,2]])
print(obj.loc["b":"c"]) # 명시적index :  b부터 c까지
print(obj.iloc[1:3]) # 암시적 index :  1부터 3전까지
obj.iloc[1:3] = 5
print(obj)

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64
b    1.0
a    0.0
d    3.0
dtype: float64
b    1.0
a    0.0
c    2.0
dtype: float64
b    1.0
c    2.0
dtype: float64
b    1.0
c    2.0
dtype: float64
a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64


In [184]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
print(data)
print(data["two"]) # 열이름으로 데이터 가져오기
print(data[["three", "one"]])
print(data[:2]) # 암시적 index를 사용해서 행 값을 출럭
print(data.iloc[:2]) # 암시적 index를 사용해서 행 값을 출럭
print(data[data["three"] > 5])
data[data < 5] = 0
print(data)
print(data.loc["Colorado"] )
print(data.loc[["Colorado", "New York"]])
print(data.loc['Colorado',["two", "three"]])
# loc, iloc로 데이터를 가져 올 때는  행열로 가져운다.

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64
          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64
          one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15
tw

In [187]:
print(data)
print(data.iloc[2]) # 암시적 사용
print(data.iloc[[2, 1]])
print(data.iloc[2, [3, 0, 1]])
print(data.iloc[[1, 2], [3, 0, 1]])
print(data.iloc[:, :3][data.three > 5])
data.loc[data.three >= 2]

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
one       8
two       9
three    10
four     11
Name: Utah, dtype: int64
          one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7
four    11
one      8
two      9
Name: Utah, dtype: int64
          four  one  two
Colorado     7    0    5
Utah        11    8    9
          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14


one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [191]:
ser = pd.Series(np.arange(3.))
print(ser)
print(ser[0])
# print(ser[-1])
print(ser.iloc[-1])

0    0.0
1    1.0
2    2.0
dtype: float64
0.0
2.0


In [192]:
# 산술 연산과 데이터 정렬
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])
s1, s2

(a    7.3
 c   -2.5
 d    3.4
 e    1.5
 dtype: float64,
 a   -2.1
 c    3.6
 e   -1.5
 f    4.0
 g    3.1
 dtype: float64)

In [193]:
s1 + s2 # index가 없으면 index를 맞추기 위해 브로드케스트를 하는데 브로드케스트된 index는 NaN값을 갖느다

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [194]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])
df1, df2

(            b    c    d
 Ohio      0.0  1.0  2.0
 Texas     3.0  4.0  5.0
 Colorado  6.0  7.0  8.0,
           b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0)

In [195]:
df1 + df2 # 행과 열이 같은 것 끼리의 연산이므로 크기가 다르면 브로드케스트를 해서 행과 열을 맞춰준다

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [196]:
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})
print(df1)
print(df2)
print(df1 + df2)

   A
0  1
1  2
   B
0  3
1  4
    A   B
0 NaN NaN
1 NaN NaN
